#
###################################
# Site wide configuration
####################################
#
title: oonlab
email: ariestiyansyah.rizky@gmail.com
description: Rizky Ariestiyansyah.
url: http://oonlab.com # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Jakarta
markdown:          kramdown
highlighter:       rouge
gems: [jekyll-paginate]
permalink:         /:categories/:year/:month/:day/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Rizky Ariestiyansyah
  avatar: profile.jpg
  job: "Researcher"
  bio: "Full-time researcher and part-time tech speaker turned to the dark side"
  email: ariestiyansyah.rizky@gmail.com
  disqus-shortname: oonlab
  twitter: ariestiyansyah #username
  facebook: edxius
  google:
    analytics: UA-48740529-1
  bing-verify:
  github: ariestiyansyah #username
  stackoverflow: 2215684/rizky-ariestiyansyah   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: ariestiyansyah #username
  instagram: ariestiyansyah

author:
  name: Rizky Ariestiyansyah
  avatar: profile.jpg
  job: "Researcher"
  bio: "Full-time researcher and part-time tech speaker turned to the dark side"
  email: ariestiyansyah.rizky@gmail.com
  disqus-shortname: oonlab
  twitter: ariestiyansyah #username
  facebook: edxius
  google:
    analytics: UA-48740529-1
  bing-verify:
  github: ariestiyansyah #username
  stackoverflow: 2215684/rizky-ariestiyansyah   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: ariestiyansyah #username
  instagram: ariestiyansyah

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
