title:  oonlab
email: ariestiyansyah.rizky@gmail.com
description: Rizky Ariestiyansyah

url: http://oonlab.com
timezone: Asia/Jakarta
baseurl: ""
paginate_path: "page:num/"
permalink: /:categories/:year/:month/:day/:title/
paginate: 5
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->

owner:
    name: Rizky Ariestiyansyah
    job: Researcher
    bio: Full-time researcher and part-time tech speaker turned to the dark side.
    avatar: profile.jpg
    github: ariestiyansyah
    twitter: ariestiyansyah
    facebook: edXius
    email: ariestiyansyah.rizky@gmail.com
    disqus-shortname: oonlab
    linkedin: ariestiyansyah
    google:
        analytics: "UA-48740529-1"
