# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ariestiyansyah
email: ariestiyansyah.rizky@gmail.com
description: >
  Lab of ariestiyansyah
logo: "http://en.gravatar.com/userimage/24637430/e79729c570147af1fb9bccec97bd5c6e.jpg"
baseurl: "http://oonlab.com" # the subpath of your site, e.g. /blog
url: "http://oonlab.com" # the base hostname & protocol for your site
paginate:	6 # The number of posts to show per page on your homepage

name: 'Rizky Ariestiyansyah'
bio: >
  Darth edXius. Full-time researcher Part-time tech speaker.
  Life is not about code.
author_image: "http://en.gravatar.com/userimage/24637430/e79729c570147af1fb9bccec97bd5c6e.jpg"
twitter_username: ariestiyansyah
github_username:  ariestiyansyah

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
