# Site settings
title: oonlab
description: Lab of ariestiyansyah
url: http://oonlab.com
baseurl: # the sub-path of your site, e.g. /blog/

disqus_shortname: oonlab
google_analytics: true
paginate: 14
permalink: /:categories/:year/:month/:day/:title/

# Links settings
links:
  - name:         Home
    url:          /
    icon:         fa-heartbeat
  - name:         About
    url:          /about
    external:     false
    icon:         fa-user-circle
  - name:         Archive
    url:          /archive
    external:     false
    external:     false
    icon:         fa-archive
  - name:         GitHub
    url:          http://github.com/ariestiyansyah
    external:     true
    icon:         fa-github

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
