# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               oonlab
tagline:             'Lab of ariestiyansyah'
description:         'oonlab is crafted with <3 by ariestiyansyah, life is not about code.'
url:                 http://oonlab.com
baseurl:             /
paginate:            7

# About/contact
author:
  name:              Rizky Ariestiyansyah
  url:               https://twitter.com/ariestiyansyah
  email:             ariestiyansyah.rizky@gmail.com
  gwebmaster:        t_k6KYgKg1o-jSCcUI-6B4e_MGY7Lv9p7oWkF1JleQk
# Custom vars
version:             2.0

# Social Media
github:				http://github.com/ariestiyansyah
twitter:			http://twitter.com/ariestiyansyah
twitter_username:	ariestiyansyah

fb_admins:          http://facebook.com/Liyan.Hdr
fb_appid:           984598984935671
avatar:             images/logo.png
# Gems on github Pages
gems:
   - jekyll-sitemap
