title:  oonlab
email: ariestiyansyah.rizky@gmail.com
description: Rizky Ariestiyansyah

url: http://oonlab.com
timezone: Asia/Jakarta
baseurl: ""
paginate_path: "page:num/"
permalink: /:categories/:year/:month/:day/:title/
disqus: oonlab

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

owner:
    name: Rizky Ariestiyansyah
    avatar: /images/profile.jpg
    github: #ariestiyansyah
    twitter: #ariestiyansyah
    facebook: #edXius
    email: ariestiyansyah.rizky@gmail.com
    disqus_shortname: 
    linkedin: #ariestiyansyah
    google:
        analytics: "UA-48740529-1"
