title: oonlab
email: ariestiyansyah.rizky@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://oonlab.com" # the base hostname & protocol for your site, e.g. http://example.com
disqus_shortname: oonlab
paginate: 12
permalink: /:categories/:year/:month/:day/:title/

highlighter: rogue

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate

navigation:
  - url: /
    title: Home
  - url: /about
    title: About
  - url: /archive
    title: Archive

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
