title:  OONLAB
description: Lab of Ariestiyansyah

url: http://oonlab.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: ariestiyansyah
   twitter: ariestiyansyah
   facebook: edXius
   email: ariestiyansyah.rizky@gmail.com

google_analytics: "UA-58263416-1"
